on:
  push:
    branches:
      - main
      - master

name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: andrewmcodes/standardrb-action
