name: Test

on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: andrewmcodes/actions/setup-ruby@main
    - name: Run Rspec
      run: bin/rspec

